name: gas_app

services:
  mongo:
    image: mongo:5.0
    container_name: mongo_gas
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  mongo_test:
    image: mongo:5.0
    container_name: mongo_gas_test
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  usuarios_api:
    build: ./Backend/Usuarios_api
    container_name: usuariosGas_api
    restart: unless-stopped
    env_file:
      - ./Backend/Usuarios_api/.env
    environment:
      MONGO_DB: GasApp_Usuarios
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Usuarios?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  unidades_api:
    build: ./Backend/Unidades_api
    container_name: unidadesGas_api
    restart: unless-stopped
    env_file:
      - ./Backend/Unidades_api/.env
    environment:
      MONGO_DB: GasApp_Unidades
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Unidades?authSource=admin
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  vendedores_api:
    build: ./Backend/Vendedores_api
    container_name: vendedoresGas_api
    restart: unless-stopped
    environment:
      MONGO_DB: GasApp_Vendedores
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Vendedores?authSource=admin
    ports:
      - "8002:8002"
    depends_on:
      - mongo

  rutas_api:
    build: ./Backend/Rutas_api
    container_name: rutasGas_api
    restart: unless-stopped
    environment:
      MONGO_DB: GasApp_Rutas
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Rutas?authSource=admin
    ports:
      - "8003:8003"
    depends_on:
      - mongo

  pedidos_api:
    build: ./Backend/Pedidos_api
    container_name: pedidosGas_api
    restart: unless-stopped
    environment:
      MONGO_DB: GasApp_Pedidos
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Pedidos?authSource=admin
      PEDIDOS_VENTAS_URL: http://ventas_api:8005
    ports:
      - "8004:8004"
    depends_on:
      - mongo

  ventas_api:
    build: ./Backend/Ventas_api
    container_name: ventasGas_api
    restart: unless-stopped
    environment:
      MONGO_DB: GasApp_Ventas
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/GasApp_Ventas?authSource=admin
    ports:
      - "8005:8005"
    depends_on:
      - mongo

  frontend:
    build: ./Frontend/gas-lp-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - ventas_api
      - usuarios_api

  usuarios_api_test:
      build: ./Backend/Usuarios_api
      container_name: usuariosGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Usuarios
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Usuarios?authSource=admin
      ports:
        - "18000:8002"
      depends_on:
        - mongo_test

  pruebas_usuarios_gas:
    build: ./Backend/Usuarios_api
    container_name: pruebas_usuariosGas_api
    command: sh -c "sleep 15 && pytest /src/pruebas_api.py -v"
    depends_on:
      - usuarios_api_test
      - mongo_test
    volumes:
      - ./Backend/Usuarios_api/src:/src
    environment:
      BASE_URL: http://usuarios_api_test:8000
      MONGO_DB: GasAppTest_Usuarios
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Usuarios?authSource=admin

  unidades_api_test:
      build: ./Backend/Unidades_api
      container_name: unidadesGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Unidades
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Unidades?authSource=admin
      ports:
        - "18001:8001"
      depends_on:
        - mongo_test

  pruebas_unidades_gas:
    build: ./Backend/Unidades_api
    container_name: pruebas_unidadesGas_api
    command: sh -c "sleep 15 && pytest /src/pruebas_api.py -v"
    depends_on:
      - unidades_api_test
      - mongo_test
    volumes:
      - ./Backend/Unidades_api/src:/src
    environment:
      BASE_URL: http://unidades_api_test:8001
      MONGO_DB: GasAppTest_Unidades
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Unidades?authSource=admin

  vendedores_api_test:
      build: ./Backend/Vendedores_api
      container_name: vendedoresGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Vendedores
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Vendedores?authSource=admin
      ports:
        - "18002:8002"
      depends_on:
        - mongo_test

  pruebas_vendedores_gas:
    build: ./Backend/Vendedores_api
    container_name: pruebas_vendedoresGas_api
    command: sh -c "sleep 15 && pytest /src/pruebas_api.py -v"
    depends_on:
      - vendedores_api_test
      - mongo_test
    volumes:
      - ./Backend/Vendedores_api/src:/src
    environment:
      BASE_URL: http://vendedores_api_test:8002
      MONGO_DB: GasAppTest_Vendedores
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Vendedores?authSource=admin

  rutas_api_test:
      build: ./Backend/Rutas_api
      container_name: rutasGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Rutas
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Rutas?authSource=admin
      ports:
        - "18003:8003"
      depends_on:
        - mongo_test

  pruebas_rutas_gas:
    build: ./Backend/Rutas_api
    container_name: pruebas_rutasGas_api
    command: sh -c "sleep 15 && pytest /src/pruebas_api.py -v"
    depends_on:
      - rutas_api_test
      - mongo_test
    volumes:
      - ./Backend/Rutas_api/src:/src
    environment:
      BASE_URL: http://rutas_api_test:8003
      MONGO_DB: GasAppTest_Rutas
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Rutas?authSource=admin

  pedidos_api_test:
      build: ./Backend/Pedidos_api
      container_name: pedidosGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Pedidos
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Pedidos?authSource=admin
        PEDIDOS_VENTAS_URL: http://ventas_api_test:8005
      ports:
        - "18004:8004"
      depends_on:
        - mongo_test

  pruebas_pedidos_gas:
    build: ./Backend/Pedidos_api
    container_name: pruebas_pedidosGas_api
    command: sh -c "sleep 30 && pytest /src/pruebas_api.py -v"
    depends_on:
      - pedidos_api_test
      - ventas_api_test
      - mongo_test
    volumes:
      - ./Backend/Pedidos_api/src:/src
    environment:
      BASE_URL: http://pedidos_api_test:8004
      MONGO_DB: GasAppTest_Pedidos
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Pedidos?authSource=admin

  ventas_api_test:
      build: ./Backend/Ventas_api
      container_name: ventasGas_api_test
      restart: unless-stopped
      environment:
        MONGO_DB: GasAppTest_Ventas
        MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Ventas?authSource=admin
      ports:
        - "18005:8005"
      depends_on:
        - mongo_test

  pruebas_ventas_gas:
    build: ./Backend/Ventas_api
    container_name: pruebas_ventasGas_api
    command: sh -c "sleep 15 && pytest /src/pruebas_api.py -v"
    depends_on:
      - ventas_api_test
      - mongo_test
    volumes:
      - ./Backend/Ventas_api/src:/src
    environment:
      BASE_URL: http://ventas_api_test:8005
      MONGO_DB: GasAppTest_Ventas
      MONGO_URI: mongodb://root:rootpassword@mongo_test:27017/GasAppTest_Ventas?authSource=admin

volumes:
  mongo_data:
  mongo_test_data: